#ifndef RESOURCE_H
#define RESOURCE_H

#define IDD_ADD_PROCESS 101
#define IDC_PROCESS_NAME 201
#define IDC_SCRIPT_PATH 202
#define IDC_BROWSE_BUTTON 203
#define IDC_TRIGGER_COMBO 204
#define IDC_TIME_INPUT 205
#define IDC_STARTUP_CHECK 206

#endif // RESOURCE_H 